# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu22.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2

    - name: Install dependencies
      with:
        arch: aarch64
        distro: ubuntu22.04
    - run: sudo apt-get install -y ruby ruby-dev build-essential clang libdbus-1-dev libgtk-3-dev libnotify-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev curl gperf bison python3-dbusmock openjdk-8-jre libc6-dev-arm64-cross linux-libc-dev-arm64-cross g++-aarch64-linux-gnu libpng-dev libavahi-compat-libdnssd-dev
    - run: sudo gem install fpm
    - run: sudo ln -s /usr/bin/fpm/fpm.ruby2.5 /usr/bin/fpm

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        arch: aarch64
        distro: ubuntu22.04
    - run: npm ci
    - run: export USE_SYSTEM_FPM=true
    - run: npm run pack:berry --if-present
