name: Build & Code Sign for macOS (Apple Silicon)

on:
  push:
    branches:
      - dev
    tags:
      - "*"

jobs:
  build_macos_arm64:
    name: Build macOS (ARM64) with Code Signing
    runs-on: macos-latest
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      
      # If you rely on electron-builder to auto-discover the signing identity in the keychain:
      CSC_IDENTITY_AUTO_DISCOVERY: "true"

    steps:
      # 1. Check out source
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Download your .p12 certificate from a private/secure link
      - name: Download .p12 certificate
        run: |
          curl -L ${{ secrets.P12_CERT_LINK }} -o certificate.p12

      # 3. Import the certificate into a temporary keychain
      - name: Import certificate
        run: |
          # Create a temporary keychain
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain

          # Import the .p12 file into the keychain
          security import certificate.p12 \
            -k build.keychain \
            -P ${{ secrets.P12_CERT_PASSWORD }} \
            -T /usr/bin/codesign \
            -T /usr/bin/productbuild

          # Remove the p12 from the filesystem (optional cleanup)
          rm certificate.p12
      
      - name: Use Node.js 18.18.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.0"

      # 5. Install dependencies
      - name: Install dependencies
        run: |
          npm ci

      # 6. Build/compile the app if needed
      - name: Build the application
        run: npm run dist:macArm

      # 8. Upload the DMG/ZIP (or .pkg) artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: STTM-Desktop-arm64
          path: |
            dist/mac-arm64/*.dmg
            dist/mac-arm64/*.zip
            dist/mac-arm64/*.pkg
